
CREATE DATABASE CAR_DEKHO;

CREATE TABLE PURCHASE_TEAM(PURCHASE_ID INT PRIMARY KEY, EMPLOYEE_NAME VARCHAR(25) NOT NULL, 
CAR_NAME VARCHAR(25) NOT NULL, SELLAR_NAME VARCHAR(25), BUYING_PRICE FLOAT NOT NULL);

CREATE TABLE SELLING_TEAM(SELLING_ID INT, FOREIGN KEY (SELLING_ID) REFERENCES PURCHASE_TEAM(PURCHASE_ID),
SALE_EMPLOYEE_NAME VARCHAR(25) NOT NULL, CAR_NAME VARCHAR(25) NOT NULL, BUYER_NAME VARCHAR(25) NOT NULL,
SELLING_PRICE FLOAT NOT NULL);

CREATE TABLE CAR_DETAILS(CAR_NAME VARCHAR(25) NOT NULL, FUEL_TYPE VARCHAR(20) NOT NULL,
CAR_AVERAGE FLOAT, CAR_DEMAND VARCHAR(15), CAR_COLOUR VARCHAR(20), GEAR_TYPE VARCHAR(15));

DESC purchase_team;
DESC selling_team;
DESC car_details;

INSERT INTO car_details()
VALUES("MARUTI_SUZUKI","PETROL",20,"BETTER","SILVER","MANUAL"),
("HAUNDAI","PETROL",19,"GOOD","SKY BLUE","MANUAL"),
("OLA","DIESEL",25,"BEST","SILVER","AUTO"),
("KIN","DIESEL",24,"BETTER","BLACK","MANUAL"),
("MARUTI_SUZUKI","DIESEL",26,"BEST","SILVER","AUTO"),
("HAUNDAI","PETROL AND CNG",30,"BEST","SILVER","MANUAL"),
("OLA","PETROL",19,"BETTER","SILVER","MANUAL"),
("KIN","PETROL AND CNG",29,"BEST","BLACK","AUTO"),
("MARUTI_SUZUKI","PETROL AND CNG",30,"BEST","SKY BLUE","AUTO"),
("HAUNDAI","DIESEL",26,"BEST","WHITE","MANUAL"),
("OLA","PETROL AND CNG",28,"BETTER","BLACK","AUTO"),
("KIN","PETROL AND CNG",29,"BEST","SILVER","MANUAL");

SELECT * FROM car_details;

UPDATE car_details
SET CAR_NAME = "MARUTI SUZUKI"
WHERE CAR_NAME = "MARUTI_SUZUKI";

SELECT * FROM car_details;

INSERT INTO purchase_team()
VALUES(101,"SACHIN","MARUTI SUZUKI","PRIYA",200000),
(102,"MAYUR","HAUNDAI","AMBIKA",210000),
(103,"YASH","OLA","RUTUJA",215000),
(104,"HARSH","KIN","SANJAY",195000),
(105,"SACHIN","MARUTI SUZUKI","RUSHIKESH",220000),
(106,"MAYUR","HAUNDAI","SHUBHAM",199000),
(107,"YASH","OLA","SANKET",205000),
(108,"HARSH","KIN","BHUSHAN",170000),
(109,"SACHIN","MARUTI SUZUKI","JAY",225000),
(110,"MAYUR","HAUNDAI","SONAL",210000),
(111,"YASH","OLA","KRISHNA",225000),
(112,"HARSH","KIN","RAM",195000);

SELECT * FROM purchase_team;

INSERT INTO selling_team()
VALUES(101,"SACHIN","MARUTI SUZUKI","SHAM",250000),
(103,"YASH","OLA","SAURABH",265000),
(105,"SACHIN","MARUTI SUZUKI","KALPANA",260000),
(107,"YASH","OLA","SHUKALA",225000),
(108,"HARSH","KIN","BHAVNA",200000),
(110,"MAYUR","HAUNDAI","PANKAJ",245000),
(112,"HARSH","KIN","PAWAN",225000),
(102,"MAYUR","HAUNDAI","GITESH",235000);

INSERT INTO selling_team()
VALUES(104,"HARSH","KIN","SANJAY",215000);

SELECT * FROM selling_team;

-- NUMBER OF TABLES 

SHOW TABLES;

--------------------------------------------------------------------------------------------------------------

-- Q1. WHICH IS THE MOST DEMANDABLE CAR

SELECT DISTINCT(CAR_NAME) AS MOST_DEMANDABLE_CAR , COUNT(CAR_NAME) AS TOTAL_SELLING FROM selling_team
GROUP BY MOST_DEMANDABLE_CAR
ORDER BY TOTAL_SELLING DESC
LIMIT 1;

-- Q2. MOST DEMANDABLE CAR ACCORDING TO GEAR TYPE, FUEL TYPE, CAR AVERAGE, CAR COLOUR.

SELECT DISTINCT(CAR_NAME) AS CAR_NAME, GEAR_TYPE, FUEL_TYPE, CAR_AVERAGE, CAR_COLOUR , CAR_DEMAND FROM car_details
WHERE CAR_DEMAND = "BEST";

-- Q3. TOTAL INCOME FROM EACH CAR.

SELECT CAR_NAME, SUM(SELLING_PRICE) AS TOTAL_INCOME FROM selling_team
GROUP BY CAR_NAME
HAVING SUM(SELLING_PRICE);

-- Q4. TOTAL BUYING COST FROM EACH CAR

SELECT CAR_NAME, SUM(BUYING_PRICE) AS TOTAL_BUYING_COST FROM purchase_team
GROUP BY CAR_NAME
HAVING SUM(BUYING_PRICE);

-- Q5. TOTAL PROFIT FROM EACH CAR AND ARRANGE THEM IN DECENDING ORDER.

SELECT SELLING_TEAM.CAR_NAME, SUM(SELLING_PRICE) AS TOTAL_SELLING_PRICE, SUM(BUYING_PRICE) AS TOTAL_BUYING_PRICE,
SUM(SELLING_PRICE) - SUM(BUYING_PRICE) AS TOTAL_PROFIT
FROM selling_team
INNER JOIN purchase_team ON selling_team.CAR_NAME = purchase_team.CAR_NAME
GROUP BY CAR_NAME
HAVING SUM(SELLING_PRICE) > SUM(BUYING_PRICE)
ORDER BY TOTAL_PROFIT DESC;


-- Q6. SHOW PROFIT PERCENTAGE OF EACH CAR

SELECT 
    ST.CAR_NAME,
    SUM(ST.SELLING_PRICE) AS TOTAL_SELLING_PRICE,
    SUM(PT.BUYING_PRICE) AS TOTAL_BUYING_PRICE,
    (SUM(ST.SELLING_PRICE) - SUM(PT.BUYING_PRICE)) AS TOTAL_PROFIT,
    CASE 
        WHEN SUM(PT.BUYING_PRICE) = 0 THEN NULL
        ELSE ROUND(((SUM(ST.SELLING_PRICE) - SUM(PT.BUYING_PRICE)) * 100.0 / SUM(PT.BUYING_PRICE)), 2)
    END AS PROFIT_PERCENTAGE
FROM 
    SELLING_TEAM ST
INNER JOIN 
    PURCHASE_TEAM PT 
ON 
    ST.SELLING_ID = PT.PURCHASE_ID
GROUP BY 
    ST.CAR_NAME
ORDER BY 
    PROFIT_PERCENTAGE DESC;
    
    
-- Q7. ADD 2 CARS WHO MAKE LOSS.

INSERT INTO selling_team()
VALUES (106,"YASH","NISSAN","KALPANA",350000),
(108,"SACHIN","FORD","SHUKALA",400000);

INSERT INTO purchase_team()
VALUES (113,"HARSH","NISSAN","AMBIKA",400000),
(114,"MAYUR","FORD","RUTUJA",450000);

SELECT * FROM selling_team;

SELECT * FROM purchase_team;

-- Q8. TOTAL LOSS FROM EACH CAR AND ARRANGE THEM IN DECENDING ORDER.

SELECT ST.CAR_NAME, SUM(SELLING_PRICE) AS TOTAL_SELLING_PRICE, SUM(BUYING_PRICE) AS TOTAL_BUYING_PRICE,
SUM(SELLING_PRICE) - SUM(BUYING_PRICE) AS TOTAL_LOSS
FROM selling_team ST
INNER JOIN purchase_team PT ON ST.CAR_NAME = PT.CAR_NAME
GROUP BY ST.CAR_NAME
HAVING SUM(SELLING_PRICE) < SUM(BUYING_PRICE)
ORDER BY TOTAL_LOSS;

-- Q9. SHOW LOSS PERCENTAGE OF EACH CAR.

SELECT 
	ST.CAR_NAME,
	SUM(SELLING_PRICE) AS TOTAL_SELLING_PRICE,
	SUM(BUYING_PRICE) AS TOTAL_SELLING_PRICE,
	SUM(SELLING_PRICE) - SUM(BUYING_PRICE) AS TOTAL_LOSS,
	CASE
		WHEN SUM(PT.BUYING_PRICE) = 0 THEN NULL
		ELSE ROUND((SUM(SELLING_PRICE) - SUM(BUYING_PRICE)) * 100.0 / SUM(BUYING_PRICE),2)
		END AS TOTAL_LOSS_PERCENTAGE
FROM SELLING_TEAM ST
INNER JOIN purchase_team PT ON ST.CAR_NAME = PT.CAR_NAME
GROUP BY ST.CAR_NAME
HAVING SUM(SELLING_PRICE) < SUM(BUYING_PRICE)
ORDER BY TOTAL_LOSS_PERCENTAGE;
	
-- 10. SHOW CAR AVERAGE AS GOOD, BETTER, BEST CATEGORY.

SELECT CAR_NAME, CAR_AVERAGE,
	CASE
		WHEN CAR_AVERAGE <= 22 THEN "GOOD"
		WHEN CAR_AVERAGE > 23 AND CAR_AVERAGE <= 26 THEN "BETTER"
		ELSE "BEST"
	END AS AVERAGE_CATEGORY
FROM car_details;





